# Generated by Django 6.0.7 on 2026-07-14 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('counter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('counter_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('called_time', models.DateTimeField(blank=True, null=True)),
                ('queue_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Called', 'Called'), ('In service', 'In service'), ('Completed', 'Completed'), ('No show', 'No show')], default='High Priority', max_length=50)),
                ('priority_level', models.CharField(choices=[('High Priority', 'High Priority'), ('Normal Priority', 'Normal Priority')], default='No show', max_length=50)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Q.counter')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Q.servicecategory')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Q.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Q.student')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.IntegerField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Q.queueticket')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Q.student')),
            ],
        ),
    ]
