# Generated by Django 6.0.7 on 2026-07-16 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Q', '0002_alter_counter_counter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Smart_Q.counter'),
        ),
        migrations.AlterField(
            model_name='queueticket',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Smart_Q.staff'),
        ),
    ]
