# Generated by Django 6.0.7 on 2026-07-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Q', '0003_alter_queueticket_counter_alter_queueticket_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='counter_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
