# Generated by Django 6.0.7 on 2026-08-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Q', '0005_rename_first_name_staff_f_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='f_name',
            new_name='first_name',
        ),
    ]
