# Generated by Django 6.0.3 on 2026-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Q', '0007_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_email',
            field=models.CharField(default='first_name+ last_name@my.richfield.ac.za', max_length=50),
        ),
    ]
