# Generated by Django 6.0.3 on 2026-09-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Q', '0008_remove_staff_department_staff_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_email',
            field=models.CharField(default='<django.db.models.fields.CharField> + <django.db.models.fields.CharField>@my.richfield.ac.za', max_length=50),
        ),
    ]
