# Generated by Django 6.0.7 on 2026-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Q', '0009_alter_staff_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='priority_level',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Normal Priority', 'Normal Priority')], default='Normal Priority', max_length=50),
        ),
        migrations.AlterField(
            model_name='queueticket',
            name='queue_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Called', 'Called'), ('In service', 'In service'), ('Completed', 'Completed'), ('No show', 'No show')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
